#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('profile', ['full', 'iterate', 'build', 'run']) and hasattr(data.values, "editorrole"):
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-editor-role-binding
subjects:
#@ if hasattr(data.values.viewerrole, "users"):
#@ for user in data.values.viewerrole.users:
- kind: User
  name: #@ user
  apiGroup: rbac.authorization.k8s.io
#@ end
#@ end
#@ if hasattr(data.values.editorrole, "groups"):
#@ for group in data.values.editorrole.groups:
- kind: Group
  name: #@ group
  apiGroup: rbac.authorization.k8s.io
#@ end
#@ end
roleRef:
  kind: ClusterRole
  name: app-editor
  apiGroup: rbac.authorization.k8s.io
